### ISSUE TITLE
Virustotal detection

### ISSUE THREAD

**Issue by LordArrin** [CoolCmd/3aIIyckaJIkaTestMem5#1]
https://www.virustotal.com/gui/file/a0e99a5b91f5a0ca91a7e47d363eb2b50b2f7e58e2f5a07c3943a36ed594219c
<img width="1250" alt="image" src="https://github.com/CoolCmd/3aIIyckaJIkaTestMem5/assets/79581469/7a4396ac-55fe-404f-86ed-80440c2e9cb0">

**Comment by CoolCmd** [comment]
Я думаю, что тупой `bkav` считает все AutoHotkey-скрипты троянами.
